/**
 * The shapes a slide can be given, grouped the way PowerPoint groups them.
 *
 * Every entry here is a preset this app draws faithfully. Offering one it
 * cannot would put a rectangle on the slide wearing another shape's name, and
 * the person would find out on somebody else's screen.
 *
 * Data rather than part of the gallery component, so a test can walk it and
 * check that claim against the geometry table.
 */

export interface ShapeGroup {
  name: string
  presets: readonly (readonly [string, string])[]
}

export const SHAPE_GROUPS: readonly ShapeGroup[] = [
  {
    name: 'Rectangles',
    presets: [
      ['rect', 'Rectangle'],
      ['roundRect', 'Rounded Rectangle'],
      ['round1Rect', 'One Rounded Corner'],
      ['round2SameRect', 'Two Rounded Corners'],
      ['round2DiagRect', 'Two Rounded Corners Diagonal'],
      ['snip1Rect', 'One Snipped Corner'],
      ['snip2SameRect', 'Two Snipped Corners'],
      ['snip2DiagRect', 'Two Snipped Corners Diagonal'],
      ['snipRoundRect', 'Snipped and Rounded Corner'],
      ['parallelogram', 'Parallelogram'],
      ['trapezoid', 'Trapezoid'],
    ],
  },
  {
    name: 'Basic',
    presets: [
      ['ellipse', 'Ellipse'],
      ['triangle', 'Triangle'],
      ['rtTriangle', 'Right Triangle'],
      ['diamond', 'Diamond'],
      ['pentagon', 'Pentagon'],
      ['hexagon', 'Hexagon'],
      ['heptagon', 'Heptagon'],
      ['octagon', 'Octagon'],
      ['decagon', 'Decagon'],
      ['dodecagon', 'Dodecagon'],
      ['plus', 'Cross'],
      ['corner', 'Corner'],
      ['diagStripe', 'Diagonal Stripe'],
      ['homePlate', 'Pentagon Arrow'],
      ['chevron', 'Chevron'],
      ['can', 'Cylinder'],
      ['cube', 'Cube'],
      ['donut', 'Donut'],
      ['noSmoking', 'No Symbol'],
      ['frame', 'Frame'],
      ['halfFrame', 'Half Frame'],
      ['bevel', 'Bevel'],
      ['plaque', 'Plaque'],
      ['foldedCorner', 'Folded Corner'],
      ['teardrop', 'Teardrop'],
      ['pie', 'Pie'],
      ['chord', 'Chord'],
      ['blockArc', 'Block Arc'],
      ['arc', 'Arc'],
      ['moon', 'Moon'],
      ['heart', 'Heart'],
      ['lightningBolt', 'Lightning Bolt'],
      ['sun', 'Sun'],
      ['smileyFace', 'Smiley Face'],
      ['cloud', 'Cloud'],
    ],
  },
  {
    name: 'Arrows',
    presets: [
      ['rightArrow', 'Right Arrow'],
      ['leftArrow', 'Left Arrow'],
      ['upArrow', 'Up Arrow'],
      ['downArrow', 'Down Arrow'],
      ['leftRightArrow', 'Left-Right Arrow'],
      ['upDownArrow', 'Up-Down Arrow'],
      ['quadArrow', 'Quad Arrow'],
      ['leftRightUpArrow', 'Left-Right-Up Arrow'],
      ['bentArrow', 'Bent Arrow'],
      ['bentUpArrow', 'Bent-Up Arrow'],
      ['uturnArrow', 'U-Turn Arrow'],
      ['notchedRightArrow', 'Notched Right Arrow'],
      ['stripedRightArrow', 'Striped Right Arrow'],
    ],
  },
  {
    name: 'Stars',
    presets: [
      ['star4', 'Four-Point Star'],
      ['star5', 'Five-Point Star'],
      ['star6', 'Six-Point Star'],
      ['star7', 'Seven-Point Star'],
      ['star8', 'Eight-Point Star'],
      ['star10', 'Ten-Point Star'],
      ['star12', 'Twelve-Point Star'],
      ['star16', 'Sixteen-Point Star'],
      ['star24', 'Twenty-Four-Point Star'],
      ['star32', 'Thirty-Two-Point Star'],
      ['irregularSeal1', 'Explosion'],
      ['irregularSeal2', 'Explosion 2'],
      ['ribbon', 'Up Ribbon'],
      ['ribbon2', 'Down Ribbon'],
      ['wave', 'Wave'],
      ['doubleWave', 'Double Wave'],
    ],
  },
  {
    name: 'Equation',
    presets: [
      ['mathPlus', 'Plus'],
      ['mathMinus', 'Minus'],
      ['mathMultiply', 'Multiply'],
      ['mathDivide', 'Divide'],
      ['mathEqual', 'Equal'],
      ['mathNotEqual', 'Not Equal'],
    ],
  },
  {
    name: 'Callouts',
    presets: [
      ['wedgeRectCallout', 'Rectangular Callout'],
      ['wedgeRoundRectCallout', 'Rounded Rectangular Callout'],
      ['wedgeEllipseCallout', 'Oval Callout'],
      ['cloudCallout', 'Cloud Callout'],
      ['borderCallout1', 'Line Callout 1'],
      ['borderCallout2', 'Line Callout 2'],
      ['borderCallout3', 'Line Callout 3'],
    ],
  },
  {
    name: 'Flowchart',
    presets: [
      ['flowChartProcess', 'Process'],
      ['flowChartAlternateProcess', 'Alternate Process'],
      ['flowChartDecision', 'Decision'],
      ['flowChartTerminator', 'Terminator'],
      ['flowChartInputOutput', 'Data'],
      ['flowChartPreparation', 'Preparation'],
      ['flowChartConnector', 'Connector'],
      ['flowChartPredefinedProcess', 'Predefined Process'],
      ['flowChartInternalStorage', 'Internal Storage'],
      ['flowChartDocument', 'Document'],
      ['flowChartMultidocument', 'Multidocument'],
      ['flowChartManualInput', 'Manual Input'],
      ['flowChartManualOperation', 'Manual Operation'],
      ['flowChartOffpageConnector', 'Off-page Connector'],
      ['flowChartPunchedCard', 'Card'],
      ['flowChartPunchedTape', 'Punched Tape'],
      ['flowChartSummingJunction', 'Summing Junction'],
      ['flowChartOr', 'Or'],
      ['flowChartCollate', 'Collate'],
      ['flowChartSort', 'Sort'],
      ['flowChartExtract', 'Extract'],
      ['flowChartMerge', 'Merge'],
      ['flowChartOnlineStorage', 'Stored Data'],
      ['flowChartDelay', 'Delay'],
      ['flowChartMagneticTape', 'Sequential Access Storage'],
      ['flowChartMagneticDisk', 'Magnetic Disk'],
      ['flowChartMagneticDrum', 'Direct Access Storage'],
      ['flowChartDisplay', 'Display'],
    ],
  },
  {
    name: 'Brackets',
    presets: [
      ['leftBracket', 'Left Bracket'],
      ['rightBracket', 'Right Bracket'],
      ['bracketPair', 'Brackets'],
      ['leftBrace', 'Left Brace'],
      ['rightBrace', 'Right Brace'],
      ['bracePair', 'Braces'],
    ],
  },
  {
    name: 'Lines',
    presets: [['line', 'Line']],
  },
]
